on: pull_request

jobs:
  test:
    # TODO switch to wine/proton
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: recursive
      - name: Configure
        run: cmake -S . -B build -G "MinGW Makefiles" -DENABLE_TESTS=ON
      - name: Build
        run: cmake --build build --parallel
      - name: Run tests
        run: ctest --test-dir build --output-on-failure
